# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
# version: '2.2'
version: '3.8'
services:

    snk-postgresql:
        image: postgres:13.4
        # volumes:
        #   - ~/volumes/jhipster/iesgamingservice/postgresql/:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=snk
          - POSTGRES_PASSWORD=
          - POSTGRES_HOST_AUTH_METHOD=trust
        # If you want to expose these ports outside your dev PC,
        # remove the "127.0.0.1:" prefix
        ports:
          - 127.0.0.1:6000:5432
          
